name: Linter
on: [push]
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint check with flake8
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run flake8
        run: |
          python -m flake8 *.py --exclude=proofread.py,venv --max-line-length=89